# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/6.x/configuration.html
scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
    totp:
        enabled: true
        issuer: 'Cauldron Overflow' # add label to auth app like google authenticator or authy
        template: security/2fa_form.html.twig # custom template

    email:
        enabled: true
        sender_email: no-reply@example.com
        mailer: App\Security\SecurityCodeMailer
        digits: 6
        template: security/2fa_form.html.twig
